// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDggp6cdiWTGm4Uo0_z3Y0IP1pDwOjD-vg',
    appId: '1:1008410208339:web:b85af308b950b759f13ea6',
    messagingSenderId: '1008410208339',
    projectId: 'reciperecive',
    authDomain: 'reciperecive.firebaseapp.com',
    storageBucket: 'reciperecive.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4lHZsYb1zjmI1OejT0CA7oQ2VK7WXJlc',
    appId: '1:1008410208339:android:0aaa162a84544968f13ea6',
    messagingSenderId: '1008410208339',
    projectId: 'reciperecive',
    storageBucket: 'reciperecive.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6_mLNTtqYxS3N4PI7gAlpj5IKwuNx_Xk',
    appId: '1:1008410208339:ios:8871f727679f3797f13ea6',
    messagingSenderId: '1008410208339',
    projectId: 'reciperecive',
    storageBucket: 'reciperecive.firebasestorage.app',
    iosBundleId: 'com.example.recipeRecive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6_mLNTtqYxS3N4PI7gAlpj5IKwuNx_Xk',
    appId: '1:1008410208339:ios:8871f727679f3797f13ea6',
    messagingSenderId: '1008410208339',
    projectId: 'reciperecive',
    storageBucket: 'reciperecive.firebasestorage.app',
    iosBundleId: 'com.example.recipeRecive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDggp6cdiWTGm4Uo0_z3Y0IP1pDwOjD-vg',
    appId: '1:1008410208339:web:5114c61bf76eea65f13ea6',
    messagingSenderId: '1008410208339',
    projectId: 'reciperecive',
    authDomain: 'reciperecive.firebaseapp.com',
    storageBucket: 'reciperecive.firebasestorage.app',
  );
}
